name: Build workflow (Gradle wrapper)

on:
  workflow_call:
    inputs:
      gradle_run:
        default: clean build -x test --no-daemon
        description: Gradle command line task for run
        required: false
        type: string
      java_distribution:
        default: 'microsoft'
        description: JDK distribution for artifact build
        required: false
        type: string
      java_version:
        default: '21'
        description: JDK version for artifact build
        required: false
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Gradle task
        uses: leo-e-org/github-workflows/.github/actions/gradle-setup@main
        with:
          gradle_run: ${{ inputs.gradle_run }}
          java_distribution: ${{ inputs.java_distribution }}
          java_version: ${{ inputs.java_version }}

      - name: Copy artifact
        run: mkdir -pv artifact && cp -rv ./build/libs/*.jar artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        with:
          name: artifact
          path: ./artifact/*
          if-no-files-found: error
          retention-days: 30
