name: Build workflow (Docker)

on:
  workflow_call:
    inputs:
      docker_base_image:
        description: Docker image name for Dockerfile
        required: true
        type: string
      image_name:
        description: Docker image name for tagging
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create artifact directory
        run: mkdir -pv artifact/
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: ./artifact/

      - name: Copy files for Docker task
        run: cp -rv ./deploy/. artifact/
      - name: Docker task
        uses: leo-ely/github-workflows/.github/actions/docker-build@main
        with:
          docker_base_image: ${{ inputs.docker_base_image }}
          image_name: ${{ inputs.image_name }}
