name: Java build using Gradle Wrapper

on:
  workflow_call:
    inputs:
      gradle_run:
        default: clean build --no-daemon
        description: Gradle command line task for run
        required: false
        type: string
      java_version:
        default: '21'
        description: JDK version for artifact build
        required: false
        type: string
      java_distribution:
        default: 'microsoft'
        description: JDK distribution for artifact build
        required: false
        type: string

env:
  PGP_KEY: ${{ secrets.PGP_SECRET_PASSPHRASE }}

jobs:
  user-variables:
    uses: ./.github/workflows/util-user-variables.yml
    secrets: inherit

  gradle-jdk:
    needs: [ user-variables ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure environment variables
        run: |
          user=$(gpg --decrypt --quiet --batch --passphrase "$PGP_KEY" --output - <(echo "${{ needs.user-variables.outputs.user }}" | base64 --decode))
          token=$(gpg --decrypt --quiet --batch --passphrase "$PGP_KEY" --output - <(echo "${{ needs.user-variables.outputs.token }}" | base64 --decode))
          echo "USER=$(echo $user)" >> $GITHUB_ENV
          echo "TOKEN=$(echo $token)" >> $GITHUB_ENV

      - name: JDK setup
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java_version }}
          distribution: ${{ inputs.java_distribution }}
          architecture: x64

      - name: Generate gradle.properties file
        run: |
          echo -e "githubUser="${{ env.USER }} > "${GITHUB_WORKSPACE}"/gradle.properties
          echo -e "githubToken="${{ env.TOKEN }} >> "${GITHUB_WORKSPACE}"/gradle.properties
      - name: Change gradlew permission
        run: chmod +x ./gradlew

      - name: Gradle setup
        uses: gradle/actions/setup-gradle@v3
      - name: Gradle build (wrapper)
        run: ./gradlew ${{ inputs.gradle_run }}

      - name: Copy artifact
        run: mkdir -pv artifact && cp -rv ./build/libs/*.jar artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        with:
          name: artifact
          path: ./artifact/*
          if-no-files-found: error
          retention-days: 30

      - name: Upload build results
        uses: actions/upload-artifact@v4
        with:
          name: Gradle build results
          path: ./build/reports/*
          retention-days: 10
