name: Super-Linter (Kotlin code base)

on:
  workflow_call:
    inputs:
      regex_include:
        required: true
        type: string

env:
  LINTER_CFG_DIR: ${{ github.workspace }}/.github/linters/
  YAML_LINT_CFG_URL: https://raw.githubusercontent.com/leo-ely/github-workflows/main/.github/linters/.yaml-lint.yml

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Copy linter configurations
        run: |
          mkdir -pv ${{ env.LINTER_CFG_DIR }}
          cd ${{ env.LINTER_CFG_DIR }}
          curl -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' ${{ env.YAML_LINT_CFG_URL }} -O

      - name: Lint code base
        uses: super-linter/super-linter/slim@v7
        env:
          DEFAULT_BRANCH: main
          FILTER_REGEX_INCLUDE: ${{ inputs.regex_include }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_KOTLIN: true
          VALIDATE_YAML: true
