name: Linter for Java code base

on:
  workflow_call:
    inputs:
      regex_include:
        required: true
        type: string

env:
  PGP_KEY: ${{ secrets.PGP_SECRET_PASSPHRASE }}
  LINTER_CFG_DIR: ${{ github.workspace }}/.github/linters/
  JAVA_LINT_CFG_URL: https://raw.githubusercontent.com/owner/github_workflows/main/.github/linters/sun_checks.xml
  YAML_LINT_CFG_URL: https://raw.githubusercontent.com/owner/github_workflows/main/.github/linters/.yaml-lint.yml

jobs:
  user-variables:
    uses: ./.github/workflows/util-user-variables.yml
    secrets: inherit

  check:
    needs: [ user-variables ]
    runs-on: ubuntu-latest
    steps:
      - name: Configure environment variables
        run: |
          token=$(gpg --decrypt --quiet --batch --passphrase "$PGP_KEY" --output - <(echo "${{ needs.user-variables.outputs.token }}" | base64 --decode))
          echo "TOKEN=$(echo $token)" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Copy linter configurations
        run: |
          mkdir -pv ${{ env.LINTER_CFG_DIR }}
          cd ${{ env.LINTER_CFG_DIR }}
          curl -H 'Authorization: Bearer ${{ env.TOKEN }}' ${{ env.YAML_LINT_CFG_URL }} -O
          curl -H 'Authorization: Bearer ${{ env.TOKEN }}' ${{ env.JAVA_LINT_CFG_URL }} -O

      - name: Lint Java code base
        uses: super-linter/super-linter/slim@v5
        env:
          DEFAULT_BRANCH: main
          FILTER_REGEX_INCLUDE: ${{ inputs.regex_include }}
          GITHUB_TOKEN: ${{ env.TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVA: true
          VALIDATE_YAML: true
