name: GitHub Workflow for Release publishing (ETL application)

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    uses: ./.github/workflows/deploy-etl.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
