name: Kubernetes application build (Gradle wrapper)

on:
  workflow_call:
    inputs:
      docker_base_image:
        default: 'Dockerfile-corretto-21'
        description: Docker image name for Dockerfile
        required: false
        type: string
      image_name:
        description: Docker image name for tagging
        required: true
        type: string
      java_distribution:
        default: 'microsoft'
        description: JDK distribution for artifact build
        required: false
        type: string
      java_version:
        default: '21'
        description: JDK version for artifact build
        required: false
        type: string

jobs:
  gradle:
    name: Gradle
    uses: ./.github/workflows/build-gradle.yml
    if: github.event_name == 'push'
    with:
      java_distribution: ${{ inputs.java_distribution }}
      java_version: ${{ inputs.java_version }}
    secrets: inherit

  docker:
    name: Docker
    needs: [ gradle ]
    uses: ./.github/workflows/build-docker.yml
    if: github.event_name == 'push'
    with:
      docker_base_image: ${{ inputs.docker_base_image }}
      image_name: ${{ inputs.image_name }}
    secrets: inherit
