name: Dependency publish (Gradle wrapper)

on:
  workflow_call:
    inputs:
      gradle_run:
        default: clean build --no-daemon
        description: Gradle command line task for run
        required: false
        type: string
      java_distribution:
        default: 'microsoft'
        description: JDK distribution for artifact build
        required: false
        type: string
      java_version:
        default: '21'
        description: JDK version for artifact build
        required: false
        type: string

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Gradle task
        id: gradle_task
        uses: leo-e-org/github-workflows/.github/actions/gradle-setup@main
        with:
          gradle_run: ${{ inputs.gradle_run }}
          java_distribution: ${{ inputs.java_distribution }}
          java_version: ${{ inputs.java_version }}

      - name: Gradle publish (wrapper)
        id: gradle-publish
        continue-on-error: true
        if: steps.gradle_task.outcome == 'success'
        run: ./gradlew publish --no-daemon
