name: Angular dependency publish using npm

on:
  workflow_call:
    inputs:
      dependency_name:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v4
      - name: Node.js ${{ matrix.node-version }} setup
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Generate .npmrc file
        run: |
          echo '@PRIVATE_ORGANIZATION:registry=https://npm.pkg.github.com/' >> ./.npmrc
          echo '//npm.pkg.github.com/:_authToken=${{ secrets.SERVICE_TOKEN }}' >> ./.npmrc
      - name: npm install
        run: npm install
        env:
          TOKEN: ${{ secrets.SERVICE_TOKEN }}

      - name: Angular dependency build
        run: ng build ${{ inputs.dependency_name }}
      - name: Angular dependency publish
        run: |
          cd ./dist/${{ inputs.dependency_name }}
          npm publish
