name: Test workflow (Gradle wrapper)

on:
  workflow_call:
    inputs:
      gradle_run:
        default: clean test --no-daemon
        description: Gradle command line task for run
        required: false
        type: string
      java_distribution:
        default: 'microsoft'
        description: JDK distribution for artifact build
        required: false
        type: string
      java_version:
        default: '21'
        description: JDK version for artifact build
        required: false
        type: string

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Gradle task
        uses: leo-ely/github-workflows/.github/actions/gradle-setup@main
        with:
          gradle_run: ${{ inputs.gradle_run }}
          java_distribution: ${{ inputs.java_distribution }}
          java_version: ${{ inputs.java_version }}
